CREATE DATABASE IF NOT EXISTS sablonic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sablonic;
CREATE TABLE users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('customer','admin','production','finance') NOT NULL DEFAULT 'customer',is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE customers(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL UNIQUE,phone VARCHAR(40),address TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE products(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,description TEXT,base_price DECIMAL(12,2) NOT NULL,is_active TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE pricing_rules(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120),rule_type VARCHAR(50),value DECIMAL(12,2),is_active TINYINT(1) DEFAULT 1);
CREATE TABLE orders(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_number VARCHAR(40) NOT NULL UNIQUE,customer_id INT UNSIGNED NOT NULL,total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,status ENUM('design_review','production','qc','packing','shipping','completed') DEFAULT 'design_review',notes TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE order_items(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,quantity INT NOT NULL,printing VARCHAR(60),unit_price DECIMAL(12,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE order_sizes(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,size VARCHAR(10),quantity INT NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE uploads(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,type VARCHAR(30),file_path VARCHAR(255),original_name VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE payments(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,amount DECIMAL(12,2) NOT NULL,method VARCHAR(50),proof_path VARCHAR(255),status ENUM('pending','verified','rejected') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE order_status_history(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,status VARCHAR(40) NOT NULL,changed_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(changed_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE production_orders(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL UNIQUE,priority INT DEFAULT 0,assigned_to INT UNSIGNED NULL,notes TEXT,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE production_tasks(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,production_order_id INT UNSIGNED NOT NULL,name VARCHAR(120),status VARCHAR(40) DEFAULT 'todo',FOREIGN KEY(production_order_id) REFERENCES production_orders(id) ON DELETE CASCADE);
CREATE TABLE qc_records(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,passed TINYINT(1) DEFAULT 0,notes TEXT,checked_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(checked_by) REFERENCES users(id) ON DELETE SET NULL);
INSERT INTO products(name,description,base_price) VALUES ('T-Shirt Premium','Cotton premium 24s',65000),('Hoodie','Fleece hoodie custom',125000),('Crewneck','Crewneck premium',110000);
-- Demo accounts. Password untuk semuanya: password
INSERT INTO users(name,email,password_hash,role) VALUES
('Admin Sablonic','admin@sablonic.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC9Q1h9iVYf6lP0K9yG','admin'),
('Production Sablonic','production@sablonic.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC9Q1h9iVYf6lP0K9yG','production'),
('Finance Sablonic','finance@sablonic.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC9Q1h9iVYf6lP0K9yG','finance'),
('Customer Demo','customer@sablonic.local','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC9Q1h9iVYf6lP0K9yG','customer');
INSERT INTO customers(user_id) SELECT id FROM users WHERE role='customer';
